language: groovy
jdk: oraclejdk8
sudo: false

env:
  global:
  - secure: iQgEvlMeYAdj5MLoN8t0uKjXW6dLfoxypO3yhhbNh5IdH5Mxe/0IESf34J2mrNdRBJh0r5tBNcELFjcunN0tZttc75nQECepQd0QE3vcId0dsQknsu7rhOmVI6WRStMgTbuw8OCTflIiyN2PbVCOv1M8pS94oeq+MpV67A2YAvlAHpRENTg+zcNKzx29tqo18DY6JXhjqKVPnTB50FDrr62cCZHR9+8Q6ITpm/ldNe3q1xUtYAiZ/AqK4k9b0WaE+y8c3pQOPMNc/LPFCpVEUbtBeoEYJQbQVa7qemF2vayzn2qzdBOqmEMKDtFfMtpzU337n+PTcGkt+ZA1FT6+zPiOMZMZ+Sa3oETrY2PrrSR3SKWeqmidsEgLYHI5Te+kmBfib3wBbbE43KidXmRpsIZakDdEnIHOcpiw67uTQ/50Yw29G2TwD9lrW74AWKsptUnlrjgQHF5GHyYcf2HfbnGyapIlAbl9KB5BDIL6NeDxNdvy6ZbaZl0GLaH/2oBDzgY9hgaue7/Js4PJXKlfsA4N3buUSFyyUmW4FgGtyBIZ5j2kist5FcG2p3Wh26ri+h0tbqZVwZbrx3YOvtyLO0q9fnJ5aKAdIJEDrWB8kl+v3mAsTCUS7K3k4G3GQSyrdgWTpwNloCl4Mj+EEkUNUn2PITdUELSXRBEUS8pX+ls=
  - secure: MjoJHYj0gMdROYM5diwDo/eI5PUSL0ye11wW42+4atb88oHaq4QPJHDWrcYrtEsgtqRryw/Q22sAKRkFrYvFx+D7WXvI6gWuq3uZ+lSX80Mn2XeW7/H+uWUuujngKkM/dorQodoFJQhzt/eltIwt4psOtuxXDBsbjVnBDnI4JJ9pqqxicuX/QxqZ2CDESsKoPjY6uEOJd4UO1iVYi7um590m8TlYZJjvT7Jk3QpHgyteCSYN1PJnlegVlVJiKgGYYl5KfIMA91ZhOzWd+bhAI+TeqRoiTnCmD2LdCjLfgXswQzMwAPlm7377s8ckyrmz6d/YexCJcXnKcmQPq+6rk8/JIXXVfG/x+/5EkbvE/aWP17loEmyq8EQU9V+8tT49Ps1wg9mMySz+GmCpf9xzvKBd/cFiQy1y1oeC58/kpn/qmymOTFt2oHgoniHEZRrg22f2Hl2i2SEc0/r+z8CM2JNV41TSM/4kIA8Tm8E3xJK9VPZsa5grr1Z7Xydh20vhrvQB0rj9TaMV3oRLzKQADUm+R73vbpSrjpOLkcAP6o6D32HR/vsYPjJ6NtvxhC1suvyFNqmSJty8UPbN7Z+5zYN0c5wBfBSFQEUmB9HcEp7ebwbe7ajk9ZXlY0THGrbq6uvpuGq7+l0qs+RXH2baL03lj7lhLy5G7eScXGN7v9g=

script:
- "./gradlew clean assemble --stacktrace"

after_success:
- "./travis-publish.sh"
